# -*- coding: utf-8 -*-
"""graphGeneration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHml_2aa5bMXX6VA0cQaq6dBqrZF_rXx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

avgAVL = open('AvgAVL.txt', 'r')
avgBST = open('AvgBST.txt','r')

bestAVL = open('BestAVL.txt','r')
bestBST = open('BestBST.txt','r')

worstAVL = open('WorstAVL.txt','r')
worstBST = open('WorstBST.txt','r')

#Average case
avgAVLArr = avgAVL.readlines()[0].rstrip("\n").split(", ")
avgAVLArr = [float(valStr) for valStr in avgAVLArr]

avgBSTArr = avgBST.readlines()[0].rstrip("\n").split(", ")
avgBSTArr = [float(valStr) for valStr in avgBSTArr]

#Best Case
bestAVLArr = bestAVL.readlines()[0].rstrip("\n").split(", ")
bestAVLArr = [int(valStr) for valStr in bestAVLArr]

bestBSTArr = bestBST.readlines()[0].rstrip("\n").split(", ")
bestBSTArr = [int(valStr) for valStr in bestBSTArr]

#Worst Case
worstAVLArr = worstAVL.readlines()[0].rstrip("\n").split(", ")
worstAVLArr = [int(valStr) for valStr in worstAVLArr]

worstBSTArr = worstBST.readlines()[0].rstrip("\n").split(", ")
worstBSTArr = [int(valStr) for valStr in worstBSTArr]

print(avgAVLArr)
print(avgBSTArr)

print(bestAVLArr)
print(bestBSTArr)

print(worstAVLArr)
print(worstBSTArr)

#for the graphs
lables = np.array(['297','594','891','1188','1485','1782','2079','2376','2673','2970'])

avgAVLArr = np.array(avgAVLArr)
avgBSTArr = np.array(avgBSTArr)

bestAVLArr = np.array(bestAVLArr)
bestBSTArr = np.array(bestBSTArr)

worstAVLArr = np.array(worstAVLArr)
worstBSTArr = np.array(worstBSTArr)

#AVG case Plot
plt.plot(lables, avgAVLArr, "b", label = "AVL")
plt.plot(lables, avgBSTArr, "r", label = "BST")
plt.legend(loc="best")
plt.title("Average Case Graph")
plt.xlabel("N")
plt.ylabel("Number of operations")
#plt.show()
plt.savefig('average.png')
files.download('average.png')

#Best case Plot
plt.plot(lables, bestAVLArr, "b", label = "AVL")
plt.plot(lables, bestBSTArr, "r", label = "BST")
plt.legend(loc="best")
plt.title("Best Case Graph")
plt.xlabel("N")
plt.ylabel("Number of operations")
#plt.show()
plt.savefig('best.png')
files.download('best.png')

#Worst case Plot
plt.plot(lables, worstAVLArr, "b", label = "AVL")
plt.plot(lables, worstBSTArr, "r", label = "BST")
plt.legend(loc="best")
plt.title("Worst Case Graph")
plt.xlabel("N")
plt.ylabel("Number of operations")
#plt.show()
plt.savefig('worst.png')
files.download('worst.png')

